[package]
name = "parse-mediawiki-sql"
version = "0.1.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
license = "MIT"
description = "A parser for SQL dumps of a MediaWiki database"
homepage = "https://github.com/Erutuon/parse-mediawiki-sql"
repository = "https://github.com/Erutuon/parse-mediawiki-sql"
readme = "README.md"
edition = "2018"

[lib]
name = "parse_mediawiki_sql"

[dependencies]
chrono = "0.4"
nom = "5.1"
bstr = "0.2"
ordered-float = "2.0"

[dev-dependencies]
memmap = "0.7"
serde_json = "1.0"
static_assertions = "1.1.0"
