[package]
name = "parse-mediawiki-sql"
version = "0.4.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
license = "MIT"
description = "A parser for SQL dumps of a MediaWiki database"
homepage = "https://github.com/Erutuon/parse-mediawiki-sql"
repository = "https://github.com/Erutuon/parse-mediawiki-sql"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
features = ["serialization"]

[lib]
name = "parse_mediawiki_sql"

[dependencies]
bstr = "0.2"
chrono = { version = "0.4", default-features = false, features = ["std"] }
joinery = "2.0.0"
nom = "6.1.2"
ordered-float = "2.0"
serde = { version = "1", features = ["derive"], optional = true }

[features]
# Can rename this to serde when namespaced features are stabilized:
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#namespaced-features
serialization = ["serde", "chrono/serde"]

[dev-dependencies]
anyhow = "1.0.32"
flate2 = "1.0.17"
memmap = "0.7"
pico-args = "0.3.4"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
smartstring = { version = "0.2.5", features = ["serde"] }
static_assertions = "1.1.0"
thiserror = "1.0.20"
